---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webproject
  labels:
    app: webproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webproject
  template:
    metadata:
      labels:
        app: webproject
    spec:
      containers:
      - name: webproject
        image: chndra/webproject:1017
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webproject
  labels:
    app: webproject
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080  # Optional: can be any value between 30000-32767
  selector:
    app: webproject
