name: PR Preview Deployment (via ArgoCD)

on:
  pull_request:
    branches: [feature]  # Corrected from 'feaure' to 'feature'
    types: [opened, synchronize, reopened]
  push:
    branches: [ "feature" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Added step to checkout the repository

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build --file Dockerfile1 -t ${{ secrets.DOCKERHUB_USERNAME }}/githubimage:latest .

      - name: Push the Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/githubimage:latest

      - name: Replace image tag in manifest
        run: |
          sed -i "s|image: chndra/githubimage:*|image: chndra/githubimage:${{ github.sha }}|" deployment.yaml  # Corrected image name

      - name: Commit and push updated manifest
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update image to chndra/githubimage:${{ github.sha }} for PR preview"  # Corrected image name
          file_pattern: deployment.yaml
          branch: feature  # Specify the branch to push changes to
